[package]
name = "cargo-release"
version = "0.12.5-alpha.0"
authors = ["Ning Sun <sunng@pm.me>"]
license = "MIT/Apache-2.0"
description = "Cargo subcommand for you to smooth your release process."
keywords = ["cargo"]
categories = ["development-tools::cargo-plugins"]
repository = "https://github.com/sunng87/cargo-release"
readme = "README.md"
edition = "2018"

[dependencies]
cargo_metadata = "0.8"
crates_io_api = "0.5"
toml = {version = "0.5", default-features = false}
toml_edit = "0.1"
serde = { version = "1.0", features = ["derive"] }
semver = "0.9.0"
semver-parser = "0.9.0"
quick-error = "1.1.0"
regex = "1.0"
bstr = "0.2.8"
termcolor = "1.0"
maplit = "1.0"
chrono = "0.4"
dirs = "2.0"
boolinator = "2.4"
difference = "2.0"
once_cell = "1.2.0"
structopt = {version = "0.3.0", default-features = false}
clap = { version = "2", default-features = false }
clap-cargo = { version = "0.2", features = ["cargo_metadata"] }
log = "0.4"
env_logger = "0.6"

[dev-dependencies]
assert_fs = "0.11"
predicates = "1.0"

[badges]
travis-ci = { repository = "sunng87/cargo-release", branch="0.12.4" }
